src/config/media/index.md, src/config/network/index.md, src/config/network/wpa_supplicant.md, src/maintenance/man.md
Some minor mistakes I found reading through.
=> Minor fixes

src/config/print/index.md
=> typo: fix CUPS acronym

src/SUMMARY.md, src/config/media/sndio.md
https://github.com/void-linux/void-packages/issues/369
=> sndio: initial documentation

src/config/network/wpa_supplicant.md
=> network/wpa_supplicant.md: Document only how to run wpa_supplicant under

src/config/shell.md
=> config/shell.md: change oksh to loksh

src/about/index.md
=> Add url for init(8)

src/SUMMARY.md, src/config/xorg/index.md, src/config/xorg/session-management.md
This is how far I have gotten in editing the Xorg page. I'd like people to take a look because I've never used anything but `nvidia` and it's been a long time. This page just looks like the weakest link right now in the documentation.
I'd also like to move Desktop Environments into seperate pages. This is just a very early first draft.
=> xorg: update xorg section

src/SUMMARY.md, src/maintenance/repositories/mirrors/tor.md
Adds instructions on using XBPS with Tor.
=> mirrors: add tor instructions

src/maintenance/packages/management.md
I added links to the man pages, a brief overview of the commands, and a reference to the xbps repo for more information.
=> packages/management.md: brief overview, and link to xbps docs

src/about/index.md, src/contributing/void-docs/style-guide.md
=> style guide: define link formatting and fix one case

src/howtoread/index.md
This is a follow-up to the issue #51
I would sincerely like input on this. I hope this is not too opinionated or in conflict with anyone else's opinions.
=> howtoread/index.md: explain scope of the handbook

src/config/network/wpa_supplicant.md
Document changes proposed here:
https://github.com/void-linux/void-packages/pull/7991
=> [HOLD] wpa_supplicant: match changes to wpa_supplicant service

src/config/kernel.md
Just a  quick update to verbiage from `expect` to `except` in the description of `vkpurge rm all`
=> Expecting except

src/SUMMARY.md, src/config/texlive.md
Today i got around to installing TeX Live, and found the wiki page about it helpful. With the wiki going away, i think it would be useful to add this information to the handbook.
=> Add 'TeX Live' section.

src/SUMMARY.md, src/xbps/packages/downgrading.md
Having recently had to downgrade `dhcpcd`, i thought it might be useful to port the wiki information about downgrading across to the handbook. :-)
=> Add section about downgrading packages.

src/about/index.md
This page seemed a bit like a wall of text to me. I did my best to organize it a little and remove some extra language.
=> about/index: organization and cleanup

src/SUMMARY.md, src/config/services/date-time.md
=> Add 'Date and Time' section.

src/contributing/void-docs/style-guide.md
* Change examples for root vs. non-root commands.
* Add text about not detailing routine commands.
This PR is further to @bobertlo's comments in #132.
=> Modify style-guide.md.

src/config/graphics/index.md, src/config/graphics/optimus.md
Explains the possible ways of configuring graphics in an Optimus laptop. Only one method is described in detail for now.
=> config/graphics/optimus: new section

src/SUMMARY.md
@xtraeme 
The new section is not showing up, forgot to add to `SUMMARY.md`
=> config/graphics/optimus: add to SUMMARY.md

src/SUMMARY.md, src/config/graphics/intel.md
Document graphics configuration for Intel GPUs.
=> config/graphics/intel: new section

src/config/graphics/index.md, src/config/graphics/optimus.md
- Document the "bumblebee" and "nouveau prime" methods under Optimus
- Add a line of text clarifying the organization of the Graphics section
=> config/graphics/optimus: add bumblebee and nouveau methods

src/config/media/pulseaudio.md
=> pulseaudio: Clarify how to use 'audio' group.

src/config/locales.md
This was prompted by https://github.com/void-linux/void-packages/pull/20737, this pull request is just to gauge whether anyone else would consider this useful.
=> locale: add application locale note

src/config/bluetooth.md, src/config/date-time.md, src/config/graphics/intel.md, src/config/graphics/optimus.md, src/config/kernel.md, src/config/media/alsa.md, src/config/media/index.md, src/config/media/sndio.md, src/config/musl.md, src/config/network/interface-names.md, src/config/network/wpa_supplicant.md, src/config/security/hashboot.md, src/config/services/configuring.md, src/config/services/logging.md, src/config/services/managing.md, src/config/services/user-services.md, src/config/wayland.md, src/config/xorg/index.md, src/contributing/void-docs/submitting.md, src/installation/guides/fde.md, src/installation/live-images/downloading.md, src/installation/live-images/partitions.md, src/installation/live-images/prep.md, src/xbps/packages/downgrading.md, src/xbps/repositories/mirrors/tor.md, src/xbps/repositories/official/debug.md
I'm posting this as a PR for review because some of these changes are opinionated.
=> spellchecking and improvement using aspell

src/contributing/void-docs/style-guide.md
Addresses [this comment](https://github.com/void-linux/void-docs/issues/190#issuecomment-613205828) by @bobertlo.
=> style-guide: Provide a general overview of appropriate content.

src/contributing/void-docs/style-guide.md
Further to @the-maldridge's comment [here](https://github.com/void-linux/void-linux.github.io/pull/89#pullrequestreview-395948473).
=> style-guide: Specify /American/ English in particular.

src/SUMMARY.md, src/config/graphical-session/graphics-drivers/index.md
Thanks @st3r4g for pointing it out c:
=> graphics-drivers: fix SUMMARY and add index in index.md

src/config/locales.md
Some corrections and a slight rewording.
=> locales: corrected file

src/config/bluetooth.md, src/config/kernel.md, src/config/locales.md, src/config/man.md, src/config/media/sndio.md, src/config/microcode.md, src/config/network/connman.md, src/config/network/dhcpcd.md, src/config/network/iwd.md, src/config/network/networkmanager.md, src/config/post-install.md, src/config/print/config.md, src/config/print/drivers.md, src/config/print/index.md, src/config/security/hashboot.md, src/contributing/usage-statistics.md, src/xbps/packages/files.md, src/xbps/packages/management.md, src/xbps/repositories/mirrors/tor.md, src/xbps/repositories/official/debug.md, src/xbps/repositories/official/installing.md
Fixes #190 
I might have removed too much stuff, please let me know if that's the case. If I have removed too little I'd like to know as well.
There have also been some additions, to allow for even more removal of duplication.
=> Fix inconsistencies in style

src/config/kernel.md
Hi,
This tiny PR will fix : 
- 1 typo in `src/config/kernel.md`
Ciao! :robot:
=> Fix typo in src/config/kernel.md

src/about/index.md, src/config/graphical-session/wayland.md
=> linkcheck: fix wrong links

src/config/print/config.md
I had that problem and it was fixed by manually entering device uri in system-config-printer. This could help someone.
=> config/print/troubleshooting: new section

src/config/services/logging.md
This is the only detail from the INSTALL.msg that was missing.
=> feat(config/services/logging): mention svlogtail

src/config/services/user-services.md
Fixed spelling and grammar issues in the original section, and made minor wording revisions.
=> per-user-services: fixed spelling and grammar, and minor rewording

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/pull_request_template.md
Add information about what issues, features and PRs we prioritise.
=> bug-report, feature-request, pull_request_template: Modify.

src/config/graphical-session/gnome.md
As recommended by @Duncaen [here](https://github.com/void-linux/void-docs/pull/249#issuecomment-625428886).
=> gnome: Modify example for testing that `gdm` works.

src/contributing/void-docs/style-guide.md
* Note need to make first man page reference a link.
* Correct URL for Void man page server.
* Improve phrasing.
@ericonr: Any objections?
=> style-guide: Multiple changes.

src/SUMMARY.md, src/config/graphical-session/graphics-drivers/index.md, src/config/security/index.md, src/contributing/index.md
=> Add Section Content headers

src/config/graphical-session/xorg.md
=> xorg: Add information about `startx`.

src/config/network/wpa_supplicant.md
=> wpa_supplicant: Remove extraneous example text.

src/SUMMARY.md, src/config/users-and-groups.md
This pull request expands the users and groups page to cover basic tasks like creating and deleting users.
I've also changed "Users and groups" to "Users and **G**roups".
=> users and groups: basic tasks to manage users and groups

src/contributing/index.md
@flexibeast @bobertlo can you take a quick look at this one? I feel like we needed to link from this page to the Join Us one.
=> contributing: add small index and link to Join Us page

src/config/graphical-session/gnome.md
Partially addresses #276.
@ericonr, does this read okay to you?
=> gnome: Restructure section.

src/xbps/troubleshooting/common-errors.md, src/xbps/troubleshooting/index.md, src/xbps/troubleshooting/static.md
=> xbps/common-errors: add section

src/xbps/packages/management.md
Fixes #235 
Is on the path to closing #201 and #103 someday.
=> packages/management: add alternatives and pkgdb

ci/check-summary.sh, ci/format.sh
=> ci/check-summary: create script

src/SUMMARY.md, src/config/graphical-session/graphics-drivers/index.md, src/config/graphical-session/graphics-drivers/nvidia.md, src/config/graphical-session/xorg.md
Seeing that my [other PR](https://github.com/void-linux/void-docs/pull/147) failed the build for some reason (I probably forgot to use -f when pushing) and no one reviewed it after the change, I decided to create this PR in hopes of it getting merged.
=> config/graphical-session/graphics-drivers: nvidia section

src/SUMMARY.md, src/config/ssd.md
My old PR had a commit on master. On my local machine, I changed the branch cause I needed to branch off master for other things. However, github doesnt let me change my branch in the PR :angry: .
This PR supersedes  #164. I implemented @flexibeast's changes.
@ericonr
=> ssd: added documentation on enabling trim

src/config/kernel.md
Added information from https://wiki.voidlinux.org/System_maintenance
=> src/config/kernel: add reason to remove old kernels

src/contributing/void-docs/index.md
* Refer to `about-handbook/index.md`.
* Modify link text for `submitting.md`.
* Fix typos.
=> void-docs/index: Multiple changes.

src/contributing/void-docs/submitting.md
* Use consistent format for placeholders.
* Change description of commit message format.
* Move mention of `mdbook serve`.
* Improve prose.
* Fix typos.
=> submitting: Multiple changes.

src/config/graphical-session/wayland.md
=> wayland: add hikari, note firefox-wayland wrapper

.gitignore, README.md, build.sh, install.sh, void-docs.md
Related to the void-docs package.
=> Add void-docs man page and building information.

void-docs.md
=> void-docs.md: small changes

src/installation/guides/fde.md
@abenson the information checks out, right?
=> fde: make UUID selection clearer

src/about/index.md
=> about/index: Reference "About this Handbook" section.

src/config/media/alsa.md
Will allow checking off the "Dmix" entry in #327.
=> alsa: Mention `dmix`.

src/about-handbook/index.md
=> about-handbook/index: Expand "Reading the Manuals" subsection.

src/SUMMARY.md, src/config/power-management.md, src/config/session-management.md
Partially addresses #327 and #337.
=> power-management: Add section.

src/SUMMARY.md, src/config/graphical-session/fonts.md
=> fonts: Add section.

src/config/network/networkmanager.md
* Improve prose.
* Remove unnecessary man page links.
* Fix heading levels.
=> networkmanager: Multiple changes.

src/installation/live-images/guide.md
* Mention features not supported by installer.
* Remove unnecessary blockquotes.
* Improve prose.
This PR will close #346.
=> live-images/guide: Multiple changes.

src/xbps/repositories/custom.md, src/xbps/repositories/signing.md
=> repositories/{custom,signing}: Tidy text, remove blockquotes.

src/config/graphical-session/graphics-drivers/optimus.md
- The prime-run script is now included in the nvidia package.
- Remove unnecessary commands.
- Remove block quotes.
Fixes #334
=> graphical-drivers/optimus: various changes.

src/xbps/repositories/mirrors/index.md
=> src/xbps/repositories/mirrors/index.md: Add more mirror links.

src/xbps/package-management.md
Needed for #368; partially addresses #201.
=> package-management: Mention how to ignore packages.

src/xbps/advanced-usage.md
=> advanced-usage: Mention `virtualpkg`.

src/xbps/repositories/mirrors/index.md
=> mirrors: Add KZ mirror.

check.sh
Following @sgn's suggestions:
- Remove subshells
- Set MISSING to empty at the start
Also added a debug message for mdbook invocation.
@flexibeast are you ok with these changes?
=> check.sh: general fixes.

src/xbps/troubleshooting/common-errors.md
* Mention "Operation not permitted" errors.
* Mention "Not Found" errors.
This PR addresses #89. Need to confirm that the error produced by incorrect system time is "Operation not permitted".
=> common-errors: Expand section.

src/config/power-management.md
Not sure this is the best way to phrase it, just wanted to get started on it.
=> power-management: acpid is not always enabled.

src/xbps/repositories/mirrors/index.md
=> mirrors/index: Add "Creating a mirror" subsection.

src/SUMMARY.md, src/config/graphical-session/icons.md
This PR addresses an issue frequently encountered by new Void users (including myself!).
=> icons: Add section.

src/config/kernel.md
Further to a conversation on IRC, a starting point for discussion - suggestions on how to further clarify this section welcome. :-)
=> kernel: Clarify that `vkpurge` removes kernels, not kernel packages.

src/config/media/sndio.md
*Before submitting a pull request, please read all the sections of the Handbook listed in [CONTRIBUTING](./CONTRIBUTING.md).*
=> sndio: add section about configuring OpenAL

src/installation/live-images/prep.md
- Remove quote blocks
- Use in-line code blocks for the dd command
- Mention the possibility of adding status=progress to dd command
=> live-images/prep: clean up.

src/config/kernel.md
What it is, how it works, what uses the values there.
=> kernel: add cmdline explanation.

src/config/media/sndio.md
- Correct "behaviour" to en_US spelling while there.
@Duncaen
=> sndio: add information about alsa-sndio.

src/config/cron.md, src/config/services/index.md
* cron:
- link to "cron" page on Wikipedia.
- provide brief introduction.
- mention crontab(1).
- mention the `crond` service.
* services/index:
- mention option of using `cron` to run something regularly, link to
"cron" section.
=> cron,services/index: Multiple changes.

src/installation/guides/arm-devices/index.md, src/installation/guides/arm-devices/platforms.md
@ericonr: Let me know if any of these changes seem to change the meaning from what was intended.
=> arm-devices/{index,platforms}: Modify phrasing.

src/SUMMARY.md, src/installation/guides/chroot.md, src/xbps/index.md, src/xbps/troubleshooting/common-issues.md, src/xbps/troubleshooting/index.md
* Rename `common-errors` to `common-issues`.
* Move "Verifying RSA keys" from `xbps/index` to `common-issues`.
* Update links.
=> xbps/<various>: Multiple changes.

src/config/services/user-services.md
=> user-services: suggest variable instead of alias.

res/build.sh, res/mdbook-latex
@ericonr: Could you please confirm this works for you also?
=> res/{build.sh,mdbook-latex}: Build A4 version of Handbook.

CONTRIBUTING.md
=> CONTRIBUTING: Mention redirects.

src/theme/index.hbs
Depends on https://github.com/void-linux/void-linux.github.io/pull/111
=> theme/index: add Manual Pages link.

src/installation/guides/arm-devices/index.md
Reported by an IRC user. @ericonr, i presume these are the intended destinations?
=> arm-devices/index: Correct internal links.

res/void-docs.1.in, res/void-docs.in
skim is simpler than fzf, but for this case it's nearly as functional.
Also:
- update man page.
- add quotes around some variables
=> void-docs: detect sk as usable fuzzy finder.

src/config/graphical-session/wayland.md, src/config/session-management.md
Also tiny "API" to "library" change.
=> wayland: add header for seat management.

src/config/graphical-session/graphics-drivers/optimus.md
Soft blocked on https://github.com/void-linux/void-infrastructure/issues/86, I'd like to link to the man page.
=> optimus: mention nvidia-smi.

src/about/index.md
Should we really pass up an opportunity like that?
=> Update void naming explaination.

res/build.sh
=> build: make fd/pandoc optional

src/theme/index.hbs
before:
```
<link rel="shortcut icon" href="">
```
after:
```
<link rel="shortcut icon" href="favicon.png">
```
=> Fix link to favicon in HTML head

src/config/date-time.md
Also mention the general ntpd service.
=> date-time: clear up language about ntp service.

src/config/graphical-session/graphics-drivers/nvidia.md
This driver has been removed from void-packages.
Before submitting a pull request, please read [CONTRIBUTING](./CONTRIBUTING.md); pull requests that do not meet the criteria described there will not be merged. Note that this repository's CONTRIBUTING contains information specific to this repository, and is not the same as CONTRIBUTING for the void-packages repository.
=> nvidia: don't recommend nvidia340 drivers anymore.

src/config/kernel.md
This is for after https://github.com/void-linux/void-packages/pull/29142.
=> kernel: reorder and add hardening section

src/installation/index.md
=> installation/index: Fix heading levels

src/xbps/repositories/mirrors/index.md
=> Adding the Easy Lee mirror

src/SUMMARY.md, src/config/graphical-session/xorg.md, src/config/media/index.md, src/config/media/pipewire.md
Before submitting a pull request, please read [CONTRIBUTING](./CONTRIBUTING.md); pull requests that do not meet the criteria described there will not be merged. Note that this repository's CONTRIBUTING contains information specific to this repository, and is not the same as CONTRIBUTING for the void-packages repository.
=> pipewire.md: add a page on setting up pipewire

src/contributing/index.md
=> contributing: move to libera for IRC.

src/config/network/index.md
=> src/config/network/index.md: Fix typo

src/installation/guides/chroot.md
Hello,
Just fixed the *"a a"* typo!
Thanks for the time.
=> src/installation/guides/chroot.md: fix typo

src/config/security/apparmor.md
void-linux/void-packages#32451 will change the default mode to complain, so the documentation needs to be fixed for that.
=> config/security/apparmor: default to complain mode

src/config/date-time.md
=> config/date-time: fix URLs

src/xbps/repositories/mirrors/index.md
Support: mirror-service@garr.it
=> Added GARR Mirror to the mirrors list

src/config/kernel.md
This simplifies the text in config/kernel to include the new linux-base package.
=> kernel.md: Simplify specific kernel version install #594

src/xbps/repositories/mirrors/index.md
=> add void.sakamoto.pl mirror

src/config/network/networkmanager.md, src/installation/live-images/prep.md
This, in conjuction with void-linux/xmandump#8, should fix all linkcheck errors
=> fix links for linkcheck lint

book.toml, res/ci/format.sh, src/xbps/repositories/mirrors/index.md
tested [here](https://github.com/void-linux/void-docs/actions/runs/2430553725)
=> fix CI for git 2.35.2+, fix outstanding CI failures

src/installation/guides/arm-devices/platforms.md
- for void-linux/void-packages#39442
=> installation/guides/arm-devices/platforms: reword for rpi-kernel merge

src/xbps/repositories/mirrors/index.md
void-linux/void-infrastructure#149
=> xbps/repositories/mirrors/index: add repo-de

src/xbps/repositories/mirrors/index.md
I’ve added this mirror in #589.
=> mirrors: Remove mirror.fit.cvut.cz

src/xbps/repositories/mirrors/index.md
=> xbps/repositories/mirrors: add voidlinux.com.br/repo/

src/xbps/repositories/mirrors/index.md
xbps/repositories/mirrors: add voidlinux.com.br/repo/
=> xbps/repositories/mirrors: add void.chililinux.com/voidlinux/

src/installation/guides/zfs.md
The link leads to a 404, and modified the link
=> About zfs.md links

src/xbps/repositories/mirrors/index.md
=> xbps/repositories/mirrors/index: group mirrors by region, sort

src/installation/guides/chroot.md, src/installation/guides/fde.md, src/installation/guides/zfs.md
- installation/guides/chroot: use xchroot for chroot install
- installation/guides/fde: use xchroot for install
- installation/guides/zfs: change chroot prompt to xchroot format
depends on:
- ~~void-linux/void-packages#37826 merge~~
- ~~void-linux/void-mklive#255 merge and new live images~~
=> Document chrooting with xchroot

src/config/graphical-session/graphics-drivers/intel.md
=> config/graphical-session/graphics-drivers/intel: fix link to kernel docs

src/config/graphical-session/graphics-drivers/optimus.md
=> graphical-drivers/optimus: add references to nvidia470

src/config/network/index.md
just a small example for bridge interfaces, not sure if i.e. mentioning how to dhcp is required.
=> network: add bridge interfaces section

src/config/media/pipewire.md
=> config/media/pipewire.md: document launching pipewire-pulse from pipewire

src/xbps/repositories/mirrors/index.md
Initial sync in progress via rsync://repo-de.voidlinux.org/voidlinux/
=> Add mirror https://ftp.cc.uoc.gr/mirrors/linux/voidlinux/

book.toml, src/theme/book.js, src/theme/css/chrome.css, src/theme/css/general.css, src/theme/css/print.css, src/theme/css/variables.css, src/theme/index.hbs
This PR builds off of @ericonr's WIP PR #581, and adds UI elements for printing and editing void-docs, as well as a
button to toggle between light and dark modes.
Examples of the updated version is live at https://void-book.qrm.cat
closes #581
=> Update theme, add light/dark mode switch

src/config/graphical-session/wayland.md
Added Qtile (qtile-wayland) to the list of Wayland compositors
=> wayland.md: Added Qtile to the list of Wayland compositors

src/installation/guides/chroot.md
merge when the next images come out
=> installation/guides/chroot: base-voidstrap -> base-container-full

src/theme/index.hbs
=> src/theme/index.hbs: close tag in search button properly

src/installation/live-images/index.md
ref: https://github.com/void-linux/void-mklive/commit/380f0fd3c4ea64b3feff4b8ffd1978def98b2af5
=> installation/live-images/index: mention other bootloader hotkeys
