src/SUMMARY.md, src/installation/prep.md
1. I am not completely satisfied with how the dd warning looked (it does not stick out much)
2. Do you think the installation section should use a table of contents and be split out into different pages? (not just for guides)
=> New installation subsection: preparing install medium

src/about/index.md
I believe `init(1)` on the *about* page should instead be `init(8)`. That's the section it is for runit's manpage and as far as I know for the traditional SysV-init as well.
Another thing that might be nice but I didn't change in this PR would be a link to the [wikipedia page for init](https://en.wikipedia.org/wiki/Init) or something similar. The passage mentions `init` as if the reader already knows what that means.
=> about: change init from section 1 to 8

src/maintenance/repositories/mirrors/changing.md
I was trying out different mirrors this morning and realized that our official mirror URLs do not include 'current' in the URL, so if you were to substitute them into this regex, it would break.
I am starting to wonder if this usage is something we want to have in our documentation, but for now I want to make sure it works!
=> mirrors/changing.md: fixed mirror syntax to be consistent

src/installation/base-requirements.md
I did a little test installing a base glibc system and a musl system into a folder, just to see how much space they take with just the `base-system` package group.
1. glibc used 675M
```
675M    /tmp/void-glibc/
```
2. musl used 561M
```
561M    /tmp/void-musl/
```
So a bit higher than 350 lol
We should probably update these recommendations to reflect that. Not sure exactly how much above the true minimum we should set this recommendation, though. I'm open to input.
=> base-requirements: modify minimum storage requirements

src/maintenance/repositories/mirrors/list.md
This is a PR to add Lysator's FTP as a void-linux mirror.
=> mirrors: add lysator mirror

src/theme/css/general.css
I noticed the sidebar font got larger. I just found the old size from the mdbook default and put it in. It looks a little crowded with the larger font.
=> general.css: revert #sidebar font-size to previous value

src/theme/css/general.css, src/theme/index.hbs
Add a hidden "skip to content" link like github has as the first  tab index.
If tab is used and the link becomes focused/active it will be visible and allows a user to skip over the menu and the sidebar to reach the content easier.
=> add skip to content link

ci/format.sh
This is just a small thing, but bugs me whenever I look at the travis log.
=> ci/format.sh: remove `go version` which is redundant

src/SUMMARY.md, src/config/bluetooth.md
I've started on the bluetooth page. Feedback appreciated.
Some extra thoughts:
1. In order for unpriviledged users to use `bluetoothctl`, they must be in either the `bluetooth` group or the `lp` group. The Void Wiki says to use the former while the Arch Wiki says to use the latter. I really don't know much about these two groups and by extension which would be the correct one to suggest to users.
Neither the Arch or Debian wikis mention the `bluetooth` group, but both briefly mention the `lp` group.
[Arch](https://wiki.archlinux.org/index.php/users_and_groups#System_groups):
> Access to parallel port devices (printers and others).
[Debian](https://wiki.debian.org/SystemGroups):
> Members of this group can enable and use printers. (The user lp is not used anymore.) …
=> config/bluetooth: add bluetooth page

src/config/kernel.md
Not sure what "dbg" was previously matching in querying "linux[34]" but it doesn't seem to match anything now; removed.
On the other hand, "hfsprogs" is matched with the query now. Ignored this match.
I also updated the sample of available kernel versions for this search.
=> config/kernel.md: update query command and available kernels

src/SUMMARY.md, src/config/network/iwd.md
I've started working on a page for IWD.
There is still expansion to be done around the general configuration and network configuration sections. Some things might have to be shuffled around as well.
I want to keep only the essentials with a few simple examples and refer users to the [upstream documentation](https://iwd.wiki.kernel.org/networkconfigurationsettings), which has good examples for more complex network configurations.
=> [WIP] config/network/iwd: create page

src/installation/live-images/guide.md
In <https://docs.voidlinux.org/installation/live-images/guide.html>, the Post Installation guide link is a 404. Fixed that link typo.
=> Fixed a link typo in the installation guide to post-install page

src/xbps/repositories/mirrors/list.md
- Added https:// where available
- Added trailing slash to provide consistency
- Removed gatech mirror: outdated
- Added cijber mirror
=> Updated list of mirrors

src/installation/live-images/partitions.md
i recently found [this section of the old wiki](https://wiki.voidlinux.org/Installation#Cfdisk_does_not_give_me_a_choice_of_partition_table_type) helpful, so would like this information added to the Handbook. :-)
=> Add note about handling pre-existing partition layout.

README.md, src/SUMMARY.md, src/contributing/void-docs/submitting.md
The repository has nothing on how to setup a local version of the docs for testing.
A couple weeks ago I was looking at the docs and thinking about contributing but I couldn't find a way to serve the docs on my localhost.
Today I thought I mess around with it a bit and made a guess based on the description of the repo ("mdbook source for docs.voidlinux.org") and installed `mdBook` from the repositories and followed the instructions at [mdBook's repo](https://github.com/rust-lang-nursery/mdBook#usage) for running.
This PR will hopefully prevent future potential contributors from running into the same issue I did. The additions to the readme are based off of the ones in mdBook's readme.
=> README.md: add building/serving instructions

src/SUMMARY.md, src/installation/guides/index.md
Now that the documentation is Live and we still do not have any content in this section I think we should remove it for now.
=> installation: remove guides stub

src/theme/css/general.css
The sidebar-toggle didn't have pointer-style cursor, even though it's a clickable element. I imagine all `.icon-button` elements should have this, so I stuck it there.
=> theme: Add cursor: pointer to .icon-button

src/config/graphics/optimus.md
The documentation for NVIDIA Optimus has a broken link which should point to an anchor on the page; these changes correct a typo which appears to be the cause of the issue.
=> ✏️ Fixes link to anchor in NVIDIA Optimus docs

src/theme/css/general.css, src/theme/css/print.css, src/theme/index.hbs
This does two things:
1. Keeps the icons if you block remote fonts like in Firefox Focus (FA icons show up as unicode squares)
2. Decreases page size. I performed a quick test on the [Downloading Images](https://docs.voidlinux.org/installation/live-images/downloading.html) page using the network tab of Firefox's Devtools with the following results:
**With font awesome:**
_Hosted (docs.voidlinux.org):_
woff2: 816.92KB
woff: 837.29KB
ttf: 404 Error<br>
_Localhost (localhost:3000):_
woff2: 809.11KB
woff: 829.50KB
ttf: 404 Error<br>
**Without font awesome (localhost only):**
svgs: 733.51KB*
no svgs: 733.66KB**<br>
\*: Uses my `svg` branch. No font awesome at all
\*\*: Uses my `master` branch with connections to the font awesome icons blocked
Visual difference: [Font …
=> Use svgs instead of font awesome

src/SUMMARY.md, src/config/microcode.md
Part of issue #129 
Unsure what is meant by "other firmware", also unsure if kernel.md is the correct place but it felt like the most suitable without creating a new section.
=> kernel.md: added microcode installation instructions to kernel section

src/config/date-time.md
The link to the "Managing Services" section on this page is broken. It should have been `../config/runit/managing.md` anyway, but as it seems like the "Runit" section was merged with "Services" anyway, `../config/services/managing.md` is now the correct destination.
=> config/date-time: fix a broken internal link

src/xbps/troubleshooting/static.md
Without XBPS_ARCH xbps-install fails mysteriously. It was also not obvious to me that musl build can be used on glibc at all.
=> troubleshooting/static: hint how to use on glibc

src/SUMMARY.md, src/config/rc-files.md
Initial draft to address #148, for feedback.
In documenting variables that can be set in `rc.conf`, this duplicates information about `HARDWARECLOCK` currently contained in the "Date and Time" section. i'm not sure if DRY is a concern here.
The information about `KEYMAP` doesn't appear elsewhere in the Handbook - i imagine many users won't necessarily think to look in this section for information about how to specify the console keymap?
=> Add section about rc files.

src/SUMMARY.md, src/config/musl.md, src/installation/base-requirements.md
Initial draft to address #130, for feedback.
i wasn't sure where to put this section in the Handbook, so i've just ended up putting it under the "Configuration" section. i've also added a link to this section from the "Base Requirements" page, with the idea of making people aware that a musl system might not be appropriate for their needs.
Also, would it be correct to say that those who need locale support should use glibc Void, rather than musl Void? (Locale support is certainly one of the reasons i use glibc rather than musl.)
=> Add "musl" section.

src/SUMMARY.md, src/config/wayland.md
Add a Wayland page, loosely based on what's available on the wiki. I can add/remove/correct information according to suggestions and opinions here.
=> config/wayland: add page

src/config/media/pulseaudio.md
This PR removes unnecessary command samples, removes outdated links, and improves the prose.
Further to a comment made by a user on #voidlinux, i feel the last paragraph could do with some expansion: what does one actually need to do with the `audio` group to allow PulseAudio to access audio devices?
=> pulseaudio: Tidy section.

src/config/network/wpa_supplicant.md
* Move WPA-PSK subsection before WEP section.
* Use 'passphrase' instead of 'key' in examples.
* Remove unneeded example re. enabling service.
* Add reference to `.../examples/.../wpa_supplicant.conf`.
* Improve prose.
=> wpa_supplicant: Reorganise section.

src/xbps/repositories/mirrors/index.md
Adds mirror to docs, necessary for https://github.com/void-linux/void-linux.github.io/pull/89
=> mirrors: add mirrors.hushan.tech

src/config/rc-files.md
The preferred way of setting localtime is by symlinking it to
/etc/localtime.
Related to https://github.com/void-linux/void-runit/pull/40
=> rc-files: remove reference to TZ

src/xbps/repositories/mirrors/index.md
=> mirrors/index: Remove 'https://youngjin.io/voidlinux/' mirror.

src/config/network/networkmanager.md
Addresses third point in #135.
=> networkmanager: Note NM users must belong to `network` group.

src/contributing/void-docs/style-guide.md, src/contributing/void-docs/submitting.md
The project moved from rust-lang-nursery to rust-lang.
=> linkcheck: fix links to mdBook

src/config/network/connman.md
- Forward slash in man links was causing bad request from server.
- Removed links to the man pages after the first one.
=> connman: fix man links and formatting

src/SUMMARY.md, src/config/graphical-session/gnome.md
Addresses #174.
This section reflects what i learned after a few hours experimenting with different scenarios in VMs:
* Merely enabling the `dbus` service is insufficient; after doing so, GNOME fails to start unless the system is first rebooted.
* The `gdm` package is required even for a `startx`-based session - again, without it, GNOME fails to start. Installing `gdm` pulls in a *lot* of dependencies, and i'm not sure which of them are strictly needed.
* If `adwaita-icon-theme` is not installed, no icons are displayed in the GNOME session, rendering it unusable.
Comments welcome!
=> [WIP] gnome: Add section.

src/SUMMARY.md, src/config/external-applications.md
Im unsure if this is something to put in the void-docs repo. I was getting a cryptic error when I used `gem install jekyll` after installing ruby from void repos. This was fixed after alot of googling and figuring out I needed to install the `ruby-devel` package.
=> External applications

src/SUMMARY.md, src/config/security/apparmor.md
It is important to outline how to enable apparmor,
because there are a few steps and one is unique to Void.
=> feat(config/security/apparmor): add section

README.md
This makes it possible to inspect different branches of void-docs using
the links. It's also shorter.
=> README: use local link instead of full GH one

src/config/graphical-session/gnome.md
=> gnome: Use `runsv` instead of `sv once` in example.

src/config/network/iwd.md
Right now the manual pages aren't links, because they aren't in man.voidlinux.org. I'm looking to rectify that.
=> Update IWD's documentation

src/config/media/alsa.md
If and when i-rinat/apulse/pull/112 gets merged, we can then link to `apulse.1` on `man.voidlinux.org` instead.
=> alsa: Link to `apulse` project README for now.

src/SUMMARY.md, src/installation/downloading.md, src/installation/live-images/downloading.md, src/installation/live-images/guide.md, src/installation/live-images/prep.md
The current verification is done through signify, and the GPG key is expired.
Fixes #232
=> downloading: remove header about using GPG

book.toml, ci/format.sh, src/config/cron.md, src/config/date-time.md, src/config/texlive.md, src/contributing/void-docs/style-guide.md, src/xbps/packages/building.md
This addition wouldn't make anyone unable to build locally, because it only uses the plugin if it finds it in the path. For CI, it makes sense to error out.
I need help with setting up CI for it, though. The current one only runs `vmdfmt`, we'd need to run `mdbook build` as well.
=> book.toml: add linkcheck plugin

src/config/graphical-session/wayland.md
Describes how to run wayland without elogind.
Information is pulled from https://wayland.freedesktop.org/building.html. Note this doesn't follow the freedesktop spec verbatim, but it allows you to run a Wayland session without elogind or dbus.
=> config/wayland: clarify how to set up wayland without elogind

book.toml, src/config/date-time.md
It was causing timeouts in CI, and sometimes locally as well.
Not very reliable.
@flexibeast looks good? I say we wait for CI.
=> book.toml: add ntp.org to exclude list

src/config/graphical-session/xorg.md
`catalyst` was removed from the repo some months ago
=> config/graphical-session/xorg: Remove catalyst

book.toml
Could be a temporary removal, adding new backends causes the creation of new folders
=> book.toml: remove linkcheck plugin

src/config/graphical-session/gnome.md
Testing in a VM found that both `gdm` and `gnome-session` require `mesa-dri` to be installed for either to start up properly. Additionally, the `xinit` package needs to be installed in order to be able to make use of `startx`.
=> gnome: Modify dependencies needed for minimal installation.

src/config/graphical-session/xorg.md
=> xorg: Mention `dbus-run-session`, to discourage use of `dbus-launch`.

src/config/graphical-session/graphics-drivers/intel.md
@jnbr can you take a look at this explanation, please? Just want to make sure it's accurate.
=> graphics-drivers/intel: add IOMMU troubleshooting

src/theme/index.hbs
The skip to content link currently points to the beginning of the table of contents. it should point to the beginning of the article.
=> src/theme/index.hbs: skip to content link skips table of contents

src/SUMMARY.md, src/xbps/troubleshooting/common-errors.md, src/xbps/troubleshooting/index.md
mdBook doesn't check links in an adequate manner.
=> xbps/trouble/common-errors: fix links

src/contributing/void-docs/style-guide.md
* Further specify link text formatting.
* Mention use of colon prior to examples.
* Describe appropriate usage of notes.
* Fix some incorrect capitalisation.
* Remove unnecessary vertical space.
This PR doesn't (yet) address whether we should specify use of "Void" or "Void Linux". From `void-docs/src`:
$ ag -c 'Void' | cut -d':' -f2 | awk '{s+=$1} END {print s}' 
104
$ ag -c 'Void Linux' | cut -d':' -f2 | awk '{s+=$1} END {print s}'
30
=> style-guide: Multiple changes.

src/SUMMARY.md, src/config/graphical-session/kde.md
This PR is based on the 'KDE' page of the old wiki.
The `kde5` package pulls in the `elogind`, `NetworkManager`, `sddm`, `udisks2` and `upower` packages, so there's no need for the user to install them manually.
The `dbus` service does not need to be enabled for a Plasma session to be started via `startx`. However, one does need to enable *both* the `dbus` and `NetworkManager` services (rather than e.g. `NetworkManager` alone) in order to use the "Networks" widget.
Since `elogind` is available, there's no need to include a 'troubleshooting' question with the answer "Install `elogind`". i presume the presence of `elogind` also means there should be no need for users to be added to the `storage` group?
i've also not included the "No shutdown, reboot buttons ..." entry, as i didn't observe …
=> kde: Add section.

src/config/network/connman.md, src/config/network/interface-names.md, src/config/network/networkmanager.md, src/contributing/void-docs/index.md, src/installation/guides/index.md, src/xbps/repositories/custom.md, src/xbps/repositories/mirrors/index.md
Every link starts with http , ./ , ../ or `#`: 
```
$ grep -RPo '\]\((?!http|..?/|#).*?\)' src/
src/contributing/void-docs/style-guide.md:](example.md#heading-text)
```
No internal link (viz links that start with a dot) contains `html`:
```
$ grep -RPo '\]\((?=html)\..*\)' src/
[no output]
```
=> Update all links to reflect style guide changes.

src/about-handbook/index.md, src/contributing/void-docs/style-guide.md
This PR is based on extant usage patterns in the Handbook.
=> about-handbook/index, style-guide: Add text about placeholders.

src/config/graphical-session/xorg.md
Closes #303
'Forcing the modesetting driver' was tested under a minimal `twm` setup with `intel` drivers, testing on different setups is welcome
=> xorg: explain DDX vs modesetting

book.toml, ci/format.sh
This reverts commit f0d5ba08932aadbf893a7762b69ab9d7419aaa49.
Fixing the deployment script makes it possible to have multiple backends
again.
Waiting for https://github.com/void-ansible-roles/mdbook/pull/1
=> Revert "book.toml: remove linkcheck plugin"

src/config/graphical-session/xorg.md
This section previously generated an html table but it does not contain tabular
data. It has been changed to an unordered list.
=> xorg.md: change table to list

src/theme/css/general.css
This PR uses the new prefers-color-scheme media query to determine if user's OS is set to dark mode (or browser is manually set to dark mode) and uses dark theme.
Let me know if I should improve something.
=> theme/css/general.css: use dark theme if prefered

src/config/media/pulseaudio.md
This PR is based on a combination of [this diagram](https://gavv.github.io/articles/pulseaudio-under-the-hood/#high-level-components) (referenced from the PulseAudio documentation [here](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/)), together with some light testing in a VM.
=> pulseaudio: Correct information re. D-BUS.

src/SUMMARY.md, src/config/services/index.md
I've changed the headings referring to service management and daemons to include a reference to runit. This makes it easier to find the section for managing runit in the handbook.
=> adding headings for runit in handbook

src/theme/css/general.css, src/theme/index.hbs
There's 2 aspects to these changes:
1. Making the docs work OK on a size that currently doesn't.  There's
some kind of overflow with the navbar, which causes the width to get
very small.
2. Making the navbar fully responsive with the left/right side.
The navbar will now automatically wrap as the screen can no longer
accommodate the right hand side.
*Before submitting a pull request, please read all the sections of the Handbook listed in [CONTRIBUTING](./CONTRIBUTING.md).*
=> Fix size issues when navbar grows

src/SUMMARY.md, src/installation/guides/chroot.md, src/installation/guides/index.md, src/installation/live-images/guide.md
This guide is not quite complete. I would like feedback on what is and isn't included, and whether any steps are confusing (or wrong).
There are three areas in particular that I am unsure of (they are currently marked in the text with TODO)
- what is the purpose of the base-voidstrap package, when would you choose it over base-minimal and when would you choose it over base-system ? (are there other metapackages that I'm unaware of someone might want to use instead?)
- installing grub for uefi can be done with only `grub-install`. The guides in the wiki include a number of switches that are either default or automatically configured. are any of these automatic configurations liable to break, should the switches be included in the instructions?
- xbps-reconfigure is used to run kernel …
=> installation via chroot guide

src/config/kernel.md
* Add information about newer-than-default kernels.
* Describe how to build DKMS modules for newer-than-default kernels.
* Fix typos.
Partially addresses #337.
=> kernel: Multiple changes.

src/theme/css/general.css
http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fdocs.voidlinux.org%2Fcss%2Fgeneral.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en
general.css sets `max-width: auto;`. the value that removes a `max-width` is `none`.
This does cause Firefox to interpret these lines of css differently so I think this merits some more scrutiny before it's merged. This ends up changing the actual width of the box in question. But its children are all floated, so it doesn't seem to make any difference.
=> src/theme/css/general.css: correction

src/about/index.md
* Mention Void focusing on stability rather than on being bleeding-edge.
* Mention runit being used for service supervision as well as init.
* Mention origin of the "Void" name.
Partially addresses #337.
=> about/index: Multiple changes.

src/config/network/firewalls.md
=> firewalls: Add `nftables` subsection.

src/xbps/advanced-usage.md, src/xbps/index.md
* index: Mention `xbps-rindex`.
* advanced-usage: Describe how to hold and repolock packages.
Partially addresses #358.
=> xbps/{index,advanced-usage}: Multiple changes.

src/installation/guides/chroot.md, src/xbps/repositories/index.md
* index: Mention locations of main repository for different system types.
* chroot: Refer to new "main repository" subsection in `index`.
Partially addresses #358.
=> repositories/index,guides/chroot: Multiple changes.

src/SUMMARY.md, src/config/network-filesystems.md
This PR is based on, and supersedes, #382.
=> network-filesystems: Add section.

src/xbps/index.md
=> xbps/index: Mention `xbps-query -f`.

src/config/index.md
The fact that mdBook requires every section to have an associated page creates annoyingly short pages such as this. We could add a "Section Contents" ToC to this page, but then i'd be concerned about the extra work keeping it in sync with the contents of SUMMARY. Suggestions for any other text that could flesh out this page to something more substantial?
=> config/index: Change wording.

src/config/network/iwd.md
* Remove now-unnecessary note about minimal kernel version.
* Convert note about wheel group membership to plain text.
* Improve phrasing.
Using `pandoc` to convert this section to a PDF results in an error due to the presence of '≥', but i assume that the note containing that character is no longer needed.
=> iwd: Tidy section.

src/installation/guides/fde.md
Using `pandoc` to convert this page to a PDF results in an error due to the presence of the line-drawing characters in the `lsblk` example. Address this by simplifying the example.
=> fde: Simplify `lsblk` example.

src/config/network-filesystems.md
Correction for the wrong names of the services that need to be activated to use nfs. Someone mistook the package names for the service names.
=> network-filesystems.md: changed wrong service names to run nfs

src/config/graphical-session/kde.md
@flexibeast does this line up with your experiments?
We had someone on reddit need to enable dbus in order to get SDDM working.
=> kde: add dbus dep for sddm.

README.md, book.toml, build.sh, mdbook-latex
Addresses #407.
This script makes use of `pandoc` and `pdfunite`, the latter being provided by the `poppler` package. There's some temporary special-casing to deal with issues that are addressed in #414 and #415 
The resulting PDF has some layout problems (e.g. on pp. 9 and 10).
i imagine we might want to incorporate this script into `build.sh`, but i've kept it separate for now, whilst it's in development. (We could, of course, keep it separate, and simply call it from `build.sh` if/when required.)
=> mdbook-latex: Add mdBook backend script.

ci/format.sh
Temporary, will be used in order to help catch timeouts.
=> ci/format: add debug var to mdbook-linkcheck.

src/config/graphical-session/kde.md
This commit adds information from [the wiki page on dolphin](https://wiki.voidlinux.org/Dolphin) to the handbook page on KDE. The tracking issue (#327) mentions that this material might be good for the KDE section, so I ported it over as best as I could.
=> kde.md: Add section on dolphin

res/mdbook-latex
Addresses issue noted in #403 [here](https://github.com/void-linux/void-docs/pull/403#issuecomment-668347838) and #407 [here](https://github.com/void-linux/void-docs/issues/407#issuecomment-668361389).
=> mdbook-latex: Fix incorrect generation of internal links.

src/installation/guides/fde.md, src/installation/live-images/guide.md, src/installation/live-images/partitions.md
Fixes some inconsistencies in capitalization of GRUB throughout the book.
Did I title this PR correctly? :) 
Also, I noticed another inconsistency (in text): `GRUB` and GRUB. Is there a rule of thumb for choosing between the two? And should a new PR be made for correcting it?
=> installation, config: capitalize mentions of GRUB

src/SUMMARY.md, src/installation/guides/arm-devices/index.md, src/installation/guides/arm-devices/platforms.md, src/installation/guides/index.md
Still work in progress, and I'm not sure I love the current structure. The `preparing your storage` header seems to be in a weird place. I wanted to add all the boards in this page as well, but it might be best to have a separate page to document their quirks.
Supersedes #385 , but I still haven't applied all comments from it.
=> Create ARM devices page

src/about/history.md
Sources:
- systemd: ccc13eae418d9f827c4505202dc3eebaccfb00aa in void-packages
- aarch64: 0f3b729b0839581b8d84b544af5d13049a15ed9a in void-packages
@leahneukirchen do you think that's a reasonable date for aarch64?
I would like to add a few more dates:
- first in person meetup - depends on someone who knows that info
- full transition to handbook - we need to decide if the wiki is being spun back up
- switch to transparent infra - suggested by maldridge, would have to find a date for it
I would like to change the date format to something more reasonable, if there's consensus for it.
=> [RFC] history: add more interesting dates.

src/config/network/connman.md
**Description**
This PR pulls in the wifi connection workflow from the old connman wiki page.
**Note**
> While this handbook does not provide a large amount of copy and paste configuration instructions, it does provide links to the man pages for the referenced software wherever possible.
Not sure if this addition is in-line with the ethos outlined here on the "About This Handbook" page, but I have found that including this in the docs can be very handy. Personally, if I'm browsing this page it's usually from mobile while I'm looking for a quick reminder to get my real system back up and connected, and it's nice to have the workflow outlined right there.
=> connman.md: Add connection workflow

src/config/services/user-services.md
The manual suggests setting the $SVDIR variable before calling `sv` on a user service directory. One such way to make user service management more convenient is to add an alias to your shell's init script. I've added an example of this using the alias `svl` to the relevant handbook page.
=> user-services.md: Added alias to manage user services.

src/xbps/repositories/index.md
From what i can tell, this PR will allow #107, which has now been open for a year, to be closed.
Link goes to `xtools.1`, since linking to `xdbg.1` won't work.
=> repositories/index: Add man page link.

src/SUMMARY.md, src/installation/guides/arm-devices/index.md, src/installation/guides/arm-devices/platforms.md
- The chroot section mentioned ROOTFS images, even though they aren't used
for any part of a XBPS installation. For a chroot install with ROOTFS,
following that page directly is the best course of action.
- Mention the appropriate qemu-<>-static commands for each arch.
- Clean up some style issues, use "Supported Platforms" instead of
"Supported platforms".
=> arm-devices/index: tidy up, fix chroot section.

src/config/bluetooth.md, src/config/graphical-session/graphics-drivers/intel.md, src/config/users-and-groups.md
These appear to be the final few remaining blockquote usages that don't adhere to the style guide, other than the one in `external-applications.md`, which is being addressed in #469.
=> <various>: Remove unnecessary blockquotes.

src/config/external-applications.md
Also remove blockquoting from Flatpak subsection.
@ericonr, let me know if using an AppImage on musl requires `gcompat`, and i'll update the PR accordingly.
=> external-applications: Mention AppImages.

src/config/network/firewalls.md
Clarifying that before running `sv up nftables` the service has to be enabled.
=> firewalls: Mention enabling nftables service.

src/installation/guides/arm-devices/platforms.md
The raspberry pi kernel disables memcg by default which breaks containers.
This commit explains how to re-enable memory cgroups.
=> platforms: mention that rbpi kernels disable memcg by default

src/xbps/repositories/mirrors/index.md
This mirror is just a different address for mirrors.dotsrc.org
Before submitting a pull request, please read [CONTRIBUTING](./CONTRIBUTING.md); pull requests that do not meet the criteria described there will not be merged. Note that this repository's CONTRIBUTING contains information specific to this repository, and is not the same as CONTRIBUTING for the void-packages repository.
=> mirrors: remove dk.archive.ubuntu.com

src/config/graphical-session/graphics-drivers/intel.md
I just spent several hours trying to troubleshoot this, so I figure its worth a callout.  It wasn't immediately obvious to me that the DDX drivers and the more specific modesetting drivers don't conflict and manual intervention is needed to put the right set on a machine.
I'm still not entirely sure which classes of intel machines are affected by this, so I added it to troubleshooting rather than the driver selection section above.
=> graphics-drivers/intel: mention DDX conflicts

src/xbps/repositories/mirrors/index.md
ftp.gnome.org == ftp.acc.umu.se
=> mirrors/index: clean inactive and repeated mirrors

src/config/network-filesystems.md
option `intr` has been ignored since Linux 2.6.25
from `nfs(5)`:
```
intr / nointr  This option is provided for backward compatibility.  It
is ignored after kernel 2.6.25.
```
=> config/network-filesystems: remove NFS option intr

src/xbps/troubleshooting/common-issues.md
Issue spotted in:
https://github.com/void-linux/void-packages/issues/26726
=> xbps/troubleshooting/common-issues: add example for outdated packages.

res/void-docs.in
pick is a fuzzy finder, and lowdown is a markdown processor, both are
written in C. This allows the void-docs-browse package to depend only on
fully portable utilities.
=> res/void-docs: support pick and lowdown.

src/config/media/sndio.md
from [void-packages#058af7e](https://github.com/void-linux/void-packages/commit/058af7e2292d2c4947b4d4ac4bf0efb2afcb469a)
>sndio support was removed by mpv#71d218e
=> config/sndio: remove mpv section

src/installation/index.md
This PR changes the docs of the installation to reflect the real file names on the server. In the docs the filename that stores shasums was called `sha256.txt`, but if you look on alpha.de.repo the file is called `sha256sum.txt.
=> installation: sha256.txt -> sha256sum.txt

src/theme/css/general.css
Constrain tables to the page width and make content scrollable. Do not restrict table size large screens (when navigation sidebar is displayed by default).
Screenshot of [a page](https://docs.voidlinux.org/installation/live-images/index.html) currently live as seen on a phone (zoomed out):
Screenshot of the same page with a scrolled table (not visible, but also "zoomed out"):
=>  theme/css/general.css: prevent tables from breaking mobile page width

src/about/index.md
Since the switch to OpenSSL is done, I don't think LibreSSL should be mentioned as a unique feature.
=> about/index: remove mention of LibreSSL

src/config/rc-files.md
This commit fixes an incorrect man page link for setfont. Closes #551.
=> rc-files.md: fixed setfont man link

src/config/package-documentation/man.md
Keep it restriced to mdocml for now, since I wasn't able to figure out
how man-db works.
=> package-documentation/man: add info about localized man pages.

src/config/media/pulseaudio.md
This commit adds a command that allows a user to manually start PulseAudio as mentioned in #496.
=> pulseaudio.md: Add manual start command

src/config/external-applications.md
This commit adds the relevant and current information from [the Steam wiki page](https://wiki.voidlinux.org/Steam) to the External Applications handbook page.
=> external-applications.md: Add section on Steam

.github/pull_request_template.md
Before submitting a pull request, please read [CONTRIBUTING](../CONTRIBUTING.md); pull requests that do not meet the criteria described there will not be merged. Note that this repository's CONTRIBUTING contains information specific to this repository, and is not the same as CONTRIBUTING for the void-packages repository.
=> pull_request_template.md: fix link to CONTRIBUTING

src/config/print/index.md
This adds a short section about IPP Everywhere printers and automatically configuring them to the docs.
Currently, this is only relevant for network printers since https://github.com/void-linux/void-packages/pull/28945 is required to make it work reliably with local printers.
=> config/print/index: add section about IPP Everywhere

README.md, res/build.sh
Given that pandoc is a haskell program, depending on it is bad due to
bootstrap and general platform compatibility concerns.
The ideal build will have the git repository available to it; builds
without the git repo will be missing date info from the man pages.
=> res/build.sh: use lowdown instead of pandoc.

src/contributing/index.md
I just saw the open port requirement for PopCorn on IRC, and since I didn't see it documented anywhere I thought it would be good to add.
=> contributing/index.md: Add port requirement for PopCorn

src/xbps/repositories/mirrors/index.md
Hi.
As of the time I put up a mirror for Void Linux, download speed was miserable and there wasn't any mirror in China. But things have improved since then. Now three universities have made their contribution in hosting Void Linux for users in China. It looks like there's no need of hosting it on my home fiber anymore.
Thanks to Void developers for your great project!
=> Remove mirror mirrors.hushan.tech.

src/config/graphical-session/wayland.md, src/config/media/pipewire.md, src/config/session-management.md
Particularly nasty because no clear error messages are shown. Tripped up quite some users on IRC and [reddit](https://old.reddit.com/r/voidlinux/comments/nq3suy/pipewirepulse_and_void_linux_and_a_pile_of_other/)
=> pipewire.md: warn about XDG_RUNTIME_DIR

src/installation/guides/fde.md
People using the FDE guide to install musl systems often forget to adjust the link properly, so link to the appropriate place. This is very similar to how the chroot guide links it.
=> installation/guides/fde: link main repository URL

src/xbps/repositories/mirrors/index.md
Currently, we mirror all files except debug/ and packages for ancient architectures (i686, armv6l).
=> mirrors: Add mirror at FIT CTU in Prague, CZ

src/config/services/user-services.md
It's a small thing but many newcomers after creating the `run` file in `/etc/sv/<username>-runsvdir` forget to make it executable. I think the reason is that to those unfamiliar with runit, it doesn't sink in that the service file are executable sh scripts rather than config files like systemd has.
I have seen multiple people facing this stumbling block both in IRC and on the subreddit so thought it's a small change that would be he helpful.
Currently I think the PR could be violating this guideline:
> Command code-blocks should not be used to describe routine tasks documented
elsewhere in this Handbook.
If this is the case feel free to let me know. I can change it to something like:
```diff
For example, you could create a service called `/etc/sv/runsvdir-<username>`
-with the following …
```
=> Add instruction for making the `run` file for per-user service executable

src/installation/guides/fde.md
* Added headers to break things up a bit
* Fix drive number as per #533
* Slight rewording
The note about GRUB not supporting LUKS2 can likely be removed with the release of Grub 2.06: https://www.phoronix.com/scan.php?page=news_item&px=GRUB-Boots-LUKS2-Disk-Encrypt
Before submitting a pull request, please read [CONTRIBUTING](./CONTRIBUTING.md); pull requests that do not meet the criteria described there will not be merged. Note that this repository's CONTRIBUTING contains information specific to this repository, and is not the same as CONTRIBUTING for the void-packages repository.
=> guide/fde: reword/fix drive number/organize

src/installation/guides/chroot.md
There doesn't seem to be a command line option for grub-install to
install there directly.
=> chroot: add info for fallback UEFI location.

src/config/services/index.md
A line-initial hyphen makes the line a bulleted list.
=> config/services: use parens instead of hyphens

src/config/graphical-session/wayland.md
Add the [river](https://github.com/riverwm/river) compositor to the list of packaged compositors
=> src/config/graphical-session/wayland.md: Add the river compositor

.github/workflows/ci.yaml, .travis.yml, res/ci/format.sh
=> ci: remove travis, add GH Actions.

src/config/media/index.md
elogind will use posix attributes to give logged in users access to
devices tagged as uaccess (such as audio and joystick input devices).
Without it, it's necessary to be in the audio group to access them.
Closes #587
@st3r4g thoughts?
=> media: add note about audio group.

.github/workflows/ci.yaml, res/ci/check-summary.sh, res/ci/format.sh
- use /bin/sh shebang for check-summary.  Works just fine and avoids
pulling in bash for the CI run.
- don't fetch upstream repository, not necessary.
- use mini-bb-x86_64-musl image to speed up container setup.
=> ci: clean-up scripts.

src/xbps/repositories/mirrors/index.md
This link was dead a couple weeks ago, and it is dead again (still?) now.
=> remove https://mirror.erickochen.nl/voidlinux/ mirror, which is down

src/xbps/troubleshooting/static.md
Only content-related change: "primary mirror in Germany" -> "primary mirror in the EU"
=> src/xbps/troubleshooting/static.md: Improve wording and formatting

src/installation/guides/chroot.md, src/installation/guides/fde.md, src/xbps/troubleshooting/common-issues.md
This removes confusing warnings that "xbps might ask you to verify the
RSA keys", and eases the installation process for the user, since no
key fingerprints have to be compared manually.
Closes https://github.com/void-linux/void-docs/issues/645
=> Network install: Copy RSA keys from installation medium to target

src/installation/live-images/index.md
The table that compares all the flavour images is a bit misleading now that there is only the xfce image
=> installation/live-images/index.md: remove references to flavour images

res/mdbook-latex, src/config/graphical-session/xorg.md, src/installation/index.md, src/installation/live-images/guide.md, src/installation/live-images/index.md
- src/installation/index.md: remove remnants of flavour images
- src/config/graphical-session/xorg.md: remove remnants of flavour images
- src/installation/live-images/guide.md: remove remnants of flavour images
- src/installation/live-images/index.md: remove remnants of flavour images, fix typo
- res/mdbook-latex: remove remnants of flavour images
=> Remove last remnants of flavour images

src/config/bluetooth.md
The bluetooth page does currently not mention the required packages for pipewire. I know that the pipewire page does state that `libspa-bluetooth` is required, but I had initially missed that and I feel like its a good idea to mention them on the bluetooth page as well.
=> src/config/bluetooth.md: mention pipewire requirements

src/config/users-and-groups.md
~~This depends on void-linux/void-packages#36238 being merged.~~
This documents the existence of the new default group.
=> config/users-and-groups.md: add plugdev to groups

src/config/media/pipewire.md
* recommend running pipewire and pipewire-pulse manually in a terminal
emulator first and then, when everything works, autostart it
solves part of #672
=> pipewire: improve documentation

res/void-docs.in
evince is installed on the GNOME isos, but xdg-open isn't, so
void-docs -p fails.
cc @ericonr
=> res/void-docs: add evince to fallback pdf viewers

.github/workflows/ci.yaml
if the first `xbps-install` fails, then no repo index is kept, causing the last `xbps-install` to fail with `Package 'mdbook-linkcheck' not found in repository pool.`
=> .github/workflows/ci.yaml: fix CI failure if xbps needs update

src/xbps/repositories/mirrors/changing.md
While changing my mirrors, I noticed that the sed command replaces a URL (`https://alpha.de.repo.voidlinux.org`) different than the one present on my system (`https://repo-default.voidlinux.org`). This PR updates the command.
=> Update default mirror URL in sed command

src/SUMMARY.md, src/config/gnupg.md
The resulting page here is going to be linked in the `gnupg2-scdaemon.INSTALL.msg` which will resolve https://github.com/void-linux/void-packages/issues/38034, together with https://github.com/void-linux/void-packages/pull/38037.
=> gnupg: add documentation about smartcard setups

.github/workflows/ci.yaml, res/ci/check-summary.sh, res/ci/format.sh
without findutils, the summary check fails: `res/ci/check-summary.sh: 8: find: not found`
=> ci: fix summary check, make prints consistent

src/installation/live-images/guide.md
related to void-linux/void-mklive#256 and void-linux/void-mklive#261
=> installation/live-images/guide: document login name restrictions

src/config/media/pipewire.md
needs [void-packages#37822](https://github.com/void-linux/void-packages/pull/37822) to be merged first
=> pipewire: mention xdg autostart files

src/installation/guides/arm-devices/platforms.md
figuring out which rpi zero should use which model is something I always forget, so why not document it for everyone
=> installation/guides/arm-devices/platforms: list rpi model support

src/xbps/repositories/mirrors/index.md
I am a fan of Void (Linux) and would like to contribute by offering a US west coast mirror.
=> Adding mirror.vofr.net out of California, USA

src/installation/guides/fde.md
a user was confused by this: https://old.reddit.com/r/voidlinux/comments/xga33g/xbpsreconfigure_f_glibclocales_not_working/
=> installation/guides/fde: clarify glibc-only commands

src/installation/live-images/guide.md
now that el-cheapo works with wpa_supplicant again, let's stop recommending to configure wifi manually.
=> installation/live-images/guide: improve wireless install guide

book.toml, src/SUMMARY.md, src/config/openpgp.md
Documentation part of https://github.com/void-linux/void-packages/pull/38406.
=> openpgp: move gnupg section and add info about opgp-card

book.toml
the exclude field is a list of regexes, so most of those links could match other urls.
Also switched to using toml raw strings.
https://michael-f-bryan.github.io/mdbook-linkcheck/mdbook_linkcheck/struct.Config.html#structfield.exclude
=> book.toml: fix regexes, add flaky mirror to linkcheck exclude

src/installation/guides/fde.md
GRUB only fully supports LUKS1 but also supports LUKS2's PBKDF2 function, which has not been clarified in the documentation before. This patch clarifies that the standard key derivation function, being Argon2i, is not supported by GRUB, avoiding confusion from potential other sources.
Closes: https://github.com/void-linux/void-docs/issues/620
=> guides/fde: Clarify GRUB LUKS2 support

src/SUMMARY.md, src/config/containers-and-vms/chroot.md, src/config/containers-and-vms/index.md, src/installation/musl.md
- based on the section of installation/musl
- remove proot
- add xchroot and bwrap
- mention flatpak and OCI containers
supercedes:
- closes #300
- I based some of my work on this
- closes #610
- I feel that this PR is too focused on providing a specific example of using bwrap, not providing general guidance
=> config/containers-and-vms/chroot: create more detailed chroot guide

.github/workflows/ci.yaml, res/ci/check-summary.sh, res/ci/commit-lint.sh, res/ci/format.sh, res/ci/linkcheck.sh
- res/ci: split CI steps into separate scripts
- res/ci/commit-lint.sh: add commit lint script
- .github/workflows/ci.yaml: split into multiple steps
=> ci: split scripts, add commit lint

src/xbps/repositories/mirrors/changing.md, src/xbps/repositories/mirrors/index.md
Marking draft until xmirror is released, but still interested in reviews
=> xbps/repositories/mirrors/changing: suggest using xmirror

src/SUMMARY.md, src/config/php.md
Hopefully this will help some users with the rocky but necessary `php` metapackage transition: https://github.com/void-linux/void-packages/pull/38536
=> config/php.md: new PHP docs to help users with the `php` metapackage transition

src/config/kernel.md
=> config/kernel: document switching between kernel series metapackages

src/config/media/pipewire.md
Now that we no longer provide `pipewire-media-session`, we can remove instructions for overriding the standard configuration to stop launching it.
=> config/media/pipewire.md: remove instructions for pipewire-media-session

src/config/media/pipewire.md, src/config/media/pulseaudio.md
- config/media/pulseaudio: remove mention of pulse system service
- if it's not recommended, why mention it? requires void-linux/void-packages#44141
- config/media/pipewire: symlink example config snippets
- instead of writing them manually (requires void-linux/void-packages#44144)
=> pipewire, pulse: small cleanups

book.toml, src/installation/live-images/index.md
for void-linux/void-mklive#295, void-linux/void-mklive#348, void-linux/void-mklive#349
=> installation/live-images/index: describe a11y features and KCL params

src/installation/guides/fde.md
Make sure to point out the appropriate device for EFI systems when trying to locate the UUID for the encrypted device.
Just adding a sentence in the UUID section for clarity for EFI systems.  I can see the argument about it's importance but since I just recently performed this on an EFI system, I saw the value of adding this in here for clarity for those who are still new to this unique process.
=> Remind reader to use correct device on EFI systems

src/installation/guides/arm-devices/index.md
proot has been kinda broken for a while and binfmt-support is easier/simpler
fixes #761
=> installation/guides/arm-devices: undocument proot for chroot install

src/installation/index.md
signify and minisign are no longer cross-compatible, and minisign is more cross-platform and will have some integrations into xbps, so it makes more sense to use minisign from now on.
=> installation/index: remove signify instructions

src/config/users-and-groups.md
Multiple descriptions were spilling into separate rows, creating a rather difficult to read table.
The row padding has been set by vmdfmt.
=> config/users-and-groups: fix formatting of groups table

src/config/graphical-session/xorg.md
=> config/graphical-session/xorg: fix grep pattern to detect modesetting driver

src/SUMMARY.md, src/config/external-applications.md, src/config/graphical-session/portals.md
seems a lot of people have had issues with this, sometimes exacerbated by the recent portals.conf change. Others have issues because they only install `-wlr`, which doesn't provide many of the common interfaces.
=> config/graphical-session/portals.md: document portal setup

src/config/graphical-session/xorg.md, src/config/media/pipewire.md, src/config/session-management.md
it seems a lot of people have trouble with this guide, and there's a lot of forks/options at each step. This rewrites the guide to streamline it into "basic setup" (wireplumber and optionally pw-pulse) and "optional setup" (everything else).
Also, this only documents the conf.d method as it's the most straightforward (IMO) and provides consistent results (wrt launch order and ensuring things are launched). I don't think we need to document every single option and overwhelm users, this guide is already very verbose.
closes #672
~~Still TODO:~~
=> config/media/pipewire: rewrite for clarity

src/xbps/repositories/mirrors/index.md
=> src/xbps/repositories/mirrors: move most mirror docs to xmirror

src/config/date-time.md
=> config/date-time: add ntpd-rs to ntp daemons

book.toml, src/installation/guides/arm-devices/platforms.md
also remove the usb boot section, as it should not be necessary as of void-linux/void-mklive#361 because partition UUIDs are now used instead of device paths.
=> installation/guides/arm-devices/platforms: mention RPi5 support

src/config/services/user-services.md, src/config/session-management.md
- config/session-management: add turnstile
- config/services/user-services: document turnstile runit services
- depends on void-linux/void-packages#44676
=> add turnstile info

src/config/users-and-groups.md
=> config/users-and-groups: fix network group description

src/theme/index.hbs
Small change to help with accessibility, by allowing the search button
to be activated using the keyboard only.
=> src/theme/index.hbs: make the search button into a button

src/config/graphical-session/graphics-drivers/intel.md
now no longer required, but some may need it
=> config/graphical-session/graphics-drivers/intel: mention xf86-video-intel

src/config/containers-and-vms/libvirt.md
Include the `qemu` package in [the libvirt section](https://docs.voidlinux.org/config/containers-and-vms/libvirt.html), preventing `virt-manager`'s "Error: No hypervisor options were found for this connection."
Could save people some troubleshooting over the simple fact that QEMU isn't installed
=> config/containers-and-vms/libvirt.md: Mention `qemu` for virt-manager/virt-install

src/theme/css/general.css
May (help) close https://github.com/void-linux/void-docs/issues/803, appends a bullet character (U+2022, •) to the end of a selected item in the sidebar for visibility.
For screen readers, this should render as "selected" instead.
(I would've tried to color the background differently but I'm not a CSS wizard and this seemed more practical.)
=> theme/css/general.css: emphasize active sidebar item

src/config/graphical-session/fonts.md, src/config/graphical-session/wayland.md
https://github.com/void-linux/void-docs/issues/802
Links to `fonts.md` under `wayland.md` and adds a hint to `fonts.md` that fonts are usually packaged with the `font-` prefix.
=> config/graphical-session: hint to font installation for compositors

src/installation/guides/arm-devices/index.md
also reorder things so it makes a bit more sense (especially for automatic binfmt registration via xbps-triggers).
=> installation/guides/arm-devices: suggest installing a specific qemu emulator

src/config/graphical-session/kde.md, src/xbps/troubleshooting/common-issues.md
rename, and some dependencies changed
see void-linux/void-packages#52464
=> config/graphical-session/kde: update docs for kde 6

src/config/external-applications.md, src/config/graphical-session/wayland.md
seems to have been a fair amount of confusion about this.
=> config/external-applications: document how java packages and alternatives work

src/config/network/iwd.md
The old link redirects to the kernel's rather funny 404 page.
=> Update link to upstream iwd documentation page

src/config/graphical-session/wayland.md
Fixup for a GTK+ link that's been breaking most of recent PRs.
[Archived version of old link](https://web.archive.org/web/20230409021006/https://wiki.gnome.org/Initiatives/Wayland/GTK%2B)
[New link](https://wiki.gnome.org/Initiatives(2f)Wayland(2f)GTK(2b).html)
=> config/graphical-session/wayland.md: fixup wayland gtk+ link

src/config/network/wpa_supplicant.md
to reduce confusion and make it easier to type out, just append it to the default conf file
=> config/network/wpa_supplicant: use the default wpa_supplicant conf

src/config/locales.md
This pull request closes issue #821.
=> Mention that Locales and Translations section is specific to glibc

src/config/containers-and-vms/lxc.md
Incus is the current community tool for easy LXC administration. LXD has been moved to canonical, relicensed (Apache 2.0 to AGPL3) and contributors are asked to sign a CLA. 
LXD package in repos is out of date, but incus is up to date. I thought we should have docs for this package. 
For now I've left the LXD section in as ahesford recommended on IRC.
=> config/containers-and-vms/lxc: document incus

src/installation/guides/arm-devices/index.md
do not merge until just before next image release
=> installation/guides/arm-devices: mention images use growpart now

src/installation/guides/chroot.md, src/installation/guides/fde.md
needs https://github.com/leahneukirchen/xtools/pull/336
fixes: #786
closes: #693
=> installation/guides: simplify chroot/fde guides with xgenfstab

book.toml, src/SUMMARY.md, src/installation/guides/arm-devices/index.md, src/installation/guides/arm-devices/pinebook-pro.md, src/installation/guides/arm-devices/raspberry-pi.md, src/installation/guides/arm-devices/thinkpad-x13s.md, src/installation/live-images/index.md
merge before next image release
=> installation/guides/arm-devices: reorganise, add new supported devices

src/SUMMARY.md, src/installation/guides/arm-devices/apple-silicon.md, src/installation/guides/arm-devices/index.md
Moved from the readme as discussed.
To do: Once this is merged, add a reference to it in asahi wiki/alt distros.
=> add apple silicon section

src/installation/guides/arm-devices/apple-silicon.md
Fixed a link, and deleted a package that is installed as dependency.
Since a user on reddit was confused about this, I mentioned explicitly that the efi partition is the one created by asahi installer (the user must not create a new one themselves).
=> asahi: fix link, explicitly mention efi partition
